# Generated by Django 5.2.12 on 2026-03-16 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created_client', 'Created Client'), ('updated_client', 'Updated Client'), ('deleted_client', 'Deleted Client'), ('created_project', 'Created Project'), ('updated_project', 'Updated Project'), ('deleted_project', 'Deleted Project'), ('created_task', 'Created Task'), ('updated_task', 'Updated Task'), ('deleted_task', 'Deleted Task'), ('completed_task', 'Completed Task'), ('created_invoice', 'Created Invoice'), ('updated_invoice', 'Updated Invoice'), ('sent_invoice', 'Sent Invoice'), ('paid_invoice', 'Marked Invoice as Paid'), ('deleted_invoice', 'Deleted Invoice'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('file_upload', 'File Upload')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
